[tool.poetry]
name = "coursework-oop"
version = "0.1.0"
description = "coursework oop"
authors = ["aleksejbelkin1017 <aleksejbelkin1017@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"